# Generated by Django 3.1.3 on 2020-11-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_budget_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='color',
            field=models.CharField(default='green', max_length=100),
        ),
    ]
